<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE TEI [
<!ELEMENT TEI (header, facsimile?, testo+)>
<!ELEMENT header (#PCDATA)>
<!ELEMENT facsimile (#PCDATA)>
<!ELEMENT testo (#PCDATA|seg)*>
<!ELEMENT seg (#PCDATA)>

<!ATTLIST header
     type CDATA #FIXED "intestazione"
     lang NMTOKEN #IMPLIED 
>
<!ATTLIST facsimile
     source CDATA #REQUIRED
     ref IDREFS #IMPLIED 
>
<!ATTLIST testo
     id ID #REQUIRED  
     type CDATA #IMPLIED 
>
]>

<TEI>
  <header> 
    contenuto testuale
  </header>
  <facsimile> 
    contenuto testuale
  </facsimile>
  <testo> 
   contenuto testuale
      <seg>
      </seg>
  </testo>
</TEI>